# Generated by Django 2.2.12 on 2020-05-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACCOUNTS',
            fields=[
                ('ACCOUNT_SOURCE_UNIQUE_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ACCOUNT_BALANCE', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMERS',
            fields=[
                ('CUSTOMER_SOURCE_UNIQUE_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER_ACOUNT_LINK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCOUNT_SOURCE_UNIQUE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVS_PoCFinCrime.ACCOUNTS')),
                ('CUSTOMER_SOURCE_UNIQUE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVS_PoCFinCrime.CUSTOMERS')),
            ],
        ),
    ]
