# Generated by Django 2.2.12 on 2020-05-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='Cuentas',
        ),
    ]
