# Generated by Django 2.2.12 on 2020-05-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ACQUISITION_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
