# Generated by Django 2.2.12 on 2020-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0005_auto_20200527_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='DATE_CLOSED',
            field=models.DateField(blank=True, null=True),
        ),
    ]
