# Generated by Django 2.2.12 on 2020-05-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0008_auto_20200527_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='CANCELLED_DATE',
            field=models.DateField(null=True),
        ),
    ]
