# Generated by Django 2.2.12 on 2020-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0009_auto_20200527_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ACCOUNT_BALANCE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
