# Generated by Django 2.2.12 on 2020-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0010_auto_20200527_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ACCOUNT_BALANCE',
            field=models.FloatField(default=0, null=True),
        ),
    ]
