# Generated by Django 2.2.12 on 2020-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0011_auto_20200527_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ACCOUNT_BALANCE',
            field=models.FloatField(default=' ', null=True),
        ),
    ]
