# Generated by Django 2.2.12 on 2020-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0012_auto_20200527_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ACCOUNT_BALANCE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
