# Generated by Django 2.2.12 on 2020-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0014_auto_20200528_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='SOURCE_TXN_NUM',
            field=models.TextField(blank=True, null=True),
        ),
    ]
