# Generated by Django 2.2.12 on 2020-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0015_auto_20200528_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='BUSINESS_SEGMENT_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
