# Generated by Django 2.2.12 on 2020-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0016_auto_20200528_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='CUSTOMER_SOURCE_UNIQUE_ID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='DELIVERY_INSTRUCTIONS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='PRIMARY_CUSTOMER_CATEGORY_CODE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='SETTLEMENT_BANK_NAME',
            field=models.TextField(blank=True, null=True),
        ),
    ]
