# Generated by Django 2.2.12 on 2020-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0017_auto_20200528_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='COLLECTED_BALANCE',
            field=models.FloatField(blank=True),
        ),
    ]
