# Generated by Django 2.2.12 on 2020-05-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0018_auto_20200528_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='DATE_CLOSED',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='DATE_OPENED',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
