# Generated by Django 2.2.12 on 2020-05-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0019_auto_20200529_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='DATE_CLOSED',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='DATE_OPENED',
            field=models.DateField(blank=True, null=True),
        ),
    ]
