# Generated by Django 2.2.12 on 2020-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0020_auto_20200529_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ACQUISITION_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
