# Generated by Django 2.2.12 on 2020-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0021_auto_20200529_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='BALANCE_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
