# Generated by Django 2.2.12 on 2020-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0022_auto_20200529_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='DEVICE_ID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
