# Generated by Django 2.2.12 on 2020-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0023_auto_20200601_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='COLLECTED_BALANCE',
            field=models.FloatField(null=True),
        ),
    ]
