# Generated by Django 2.2.12 on 2020-06-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0024_auto_20200601_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='COLLECTED_BALANCE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
