# Generated by Django 2.2.12 on 2020-06-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVS_PoCFinCrime', '0027_auto_20200601_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='PRODUCT_SOURCE_TYPE_CODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
